export { aboutStyles } from "./sections/about";
export { appStyles } from "./sections/app";
export { blogStyles, blogToneStyles } from "./sections/blog";
export { contactStyles } from "./sections/contact";
export { documentsStyles } from "./sections/documents";
export { footerStyles } from "./sections/footer";
export { homeStyles } from "./sections/home";
export { navbarStyles } from "./sections/navbar";
export { portfolioStyles, portfolioToneStyles } from "./sections/portfolio";
export { resumeStyles } from "./sections/resume";
export { servicesStyles, serviceToneStyles } from "./sections/services";
